services:
  flask32:
    platform: "linux/386"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: bash -c "./scripts/build.sh && ./scripts/run.sh"
